name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/docker-image.yml
      - 'Dockerfile'

jobs:
  push_to_registry:
    name: push docker image to the docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #DO NOT CHANGE
          password: ${{ secrets.DOCKER_PASSWORD }} #DO NOT CHANGE

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alinahameed/dsci310-ia3-alinahameed-docker:latest